### ISSUE TITLE
[question] how to validate json body with decorator

### ISSUE THREAD

**Issue by zingmane** [nhttp/nhttp_validator#1]
I have a question, maybe I doing it wrong...

I try to set up nhttp server with swagger API doc and json schema validation.  With some of your cool packages `nhttp` , `nhttp_swagger`, `nhttp_controler` and `nhttp_validator`.

```ts
import {  Validate,  validate } from "https://deno.land/x/nhttp_validator@0.3.0/mod.ts";

// validation via passing the validator manually with controller registry is working
app.use("/api", validate(Category), addControllers([CategoryController]));

// validation via Validate decorator isn't working
export class Category {
  @IsString()
  name!: string;

  @IsNumber()
  id!: number;
}

@ApiDocument({ name: "category" })
@Controller("/category")
export class CategoryController extends BaseController {
  @ApiRequestBody({
    description: "category to create",
    required: true,
    schema: Category,
  })
  @ApiOperation({ summary: "create category" })
  @Validate(Category)
  @Post()
  save(rev: RequestEvent) {
    const { body } = rev;
    return body;
  }
}
```

Is there an issue or am I missing something? Thx in advance.

btw.
I figured out that import ordering is important if I use `validationMetadatasToSchemas`. If that dependency is not imported before all the controllers, I get an error `Error starting server.  TypeError: Cannot read properties of undefined (reading 'map')`. Anyway, just FYI. Maybe that is worth a mentioing somewhere in the docs, because it took me an hour or two to figure that out.

**Comment by zingmane** [comment]
It seems to be a problem with the newest version of `nhttp_controller@0.8.0`. With version `nhttp_controller@0.7.0` validation is working in both ways.

**Comment by herudi** [comment]
well, you are right. for automatic `@ApiRequestBody`, it requires additional library `class-validator-jsonschema`.

```ts
import { validationMetadatasToSchemas } from "npm:class-validator-jsonschema";
...
// add to this options.
swagger(app, "/api-docs", document, { validationMetadatasToSchemas });
```

btw, for latest version 1.1.12 or higher, move to 3rd party lib. the advantage for developer experience, is that there is no need to worry about the version of the library.

Docs:
Controller => https://nhttp.deno.dev/docs/3rd-party-lib/routing-controller
Swagger => https://nhttp.deno.dev/docs/3rd-party-lib/swagger
Validator => https://nhttp.deno.dev/docs/3rd-party-lib/class-validator

**Comment by zingmane** [comment]
perfect, with import via `nhttp@1.1.12/lib` validation is working. 
Thanks for your quick reply. 👍🚀
